language: c

before_install: 
 - sudo add-apt-repository ppa:mwild1/ppa -y
 - sudo apt-get update -y
 - sudo apt-get install luajit -y --force-yes
 - git submodule update --init

script:
 - make
 - make test
